title: Pepinazo TRASSH
author: Otundreas
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Este es mi peazo blog. A fliparlo people

# social links
twitter_username: afaf # DO NOT include the @ character, or else the build will fail!
github_username:  otundra # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
